#!/bin/bash
#
# AMSTer: SAR & InSAR Automated Mass processing Software for Multidimensional Time series
#

TSFILE=$(basename "$1")

# files are generated by msbas2 and are as follow: 
# MSBAS_ROW_COL_RADIUS.ts
# and are filled with lines such as 
# eg : 		20151205T041135 2015.926506 0.000000 0.000000
# that is : dummy 			decimadate 	up 		 ew

ROW=`echo ${TSFILE} | cut -d _ -f 2`
COL=`echo ${TSFILE} | cut -d _ -f 3`
RAD=`echo ${TSFILE} | cut -d _ -f 4 | cut -d . -f 1`

/opt/local/bin/gnuplot << EOF
	set terminal postscript color eps enhanced  "Helvetica,24"
	set output "${TSFILE}.eps"
#	set output "lcurveNoLog.eps"
	set   autoscale                        # scale axes automatically
    unset label                            # remove any previous labels
    set xtic auto                          # set xtics automatically
    set ytic auto                          # set ytics automatically
    set title "Pixel ${ROW}-${COL}, radius ${RAD}"
    set xlabel "Date" font "Helvetica,24"
    set ylabel "up and ew [m]" font "Helvetica,24"
	#set ytics font "Helvetica,24" 
	set xtics font "Helvetica,16" 
	#set size 1.5,1.5
	#set pointsize 1
	#set xtics 0.5	
	set key left top

	set timestamp "Created by AMSTer at ECGS on: %d/%m/%y %H:%M " font "Helvetica,8" textcolor rgbcolor "#2a2a2a" 

#'plot "lcurve.txt" using 2:3 notitle with linespoints'
plot "${TSFILE}" u 2:3 title '  ew', "${TSFILE}" u 2:4  title '  up' 


#pplot 'span.txt' with vectors nohead lt 1 lw 1.5 lc rgb '#4D4D4D' notitle, 'span1.txt' with points pt 7 ps 1.5 lc rgb '#4D4D4D' notitle
#plot "lcurveNoLog.txt" u 2:3:1 w labels offset character 0,character 1 tc rgb "blue" notitle, "lcurveNoLog.txt" u 2:3 with lp notitle



EOF
gmt psconvert -Tj -A -E300 ${TSFILE}.eps

